"""
Hermes Synthesizer — merges parallel agent outputs into one answer.
Preserves evidence classes, carries citations, surfaces confirm-token actions.
"""
import json
from typing import Optional

from .planner import PlannerDecision
from services.ai_provider import model_for_agent, multilingual_suffix


SYNTHESIZER_SYSTEM = """You are Hermes, the PAL health assistant synthesizer.
Your job: merge the specialist agent outputs into ONE clear, honest answer.

Rules:
- Apply the evidence contract to every fact you surface:
  source_backed | user_canonical | inferred | statistical | unknown.
- Carry all citations from agent outputs.
- If agents disagree on something clinical, surface the disagreement honestly;
  recommend the patient speak with their clinician.
- Never diagnose, never prescribe, never interpret imaging.
- For any pending actions (booking, messaging), surface them as explicit prompts
  with confirm-token flows — never auto-send.
- Say "no good evidence found" when evidence is absent; never confabulate.
- Language: plain, warm, non-shaming. Newsreader-quality prose.
- End with provenance summary: "Why do I think this?" answered briefly."""

SYNTHESIZER_PROMPT_TEMPLATE = """Patient query: {query}
{coversation_history_section}
Agent results:
{agent_results_json}

{record_context_section}

Synthesize one answer following the rules above. Return JSON:
{{
  "answer_text": "...",
  "evidence_classes": {{"claim": "class", ...}},
  "citations": [{{"title": "...", "source": "...", "url": "..."}}],
  "pending_actions": [{{"type": "booking|messaging", "description": "...", "confirm_token_required": true}}],
  "provenance_summary": "...",
  "clinical_disagreement": null | "description of disagreement"
}}"""


async def synthesize(
    query: str,
    agent_results: dict[str, dict],
    plan: PlannerDecision,
    ai_client,
    record_context: Optional[dict] = None,
    is_second_opinion: bool = False,
    multilingual_lang: Optional[str] = None,
) -> dict:
    record_section = ""
    if record_context:
        record_section = f"Personal record context (retrieved slice):\n{json.dumps(record_context, indent=2)}"

    history_section = ""
    if conversation_history:
        history_section = f"""**Previous conversation context:**
{conversation_history}

Use this context to maintain continuity. If the user is confirming something from a previous turn, understand what they're confirming.
"""

    prompt = SYNTHESIZER_PROMPT_TEMPLATE.format(
        query=query,
        conversation_history_section=history_section,
        agent_results_json=json.dumps(agent_results, indent=2, default=str),
        record_context_section=record_section,
    )

    system = SYNTHESIZER_SYSTEM + multilingual_suffix(multilingual_lang)
    response = await ai_client.messages.create(
        model=model_for_agent("synthesizer", is_second_opinion),
        max_tokens=2048,
        system=system,
        messages=[{"role": "user", "content": prompt}],
    )

    raw = response.content[0].text if response.content else "{}"
    try:
        # Extract JSON from the response
        start = raw.find("{")
        end = raw.rfind("}") + 1
        return json.loads(raw[start:end])
    except Exception:
        return {
            "answer_text": raw,
            "evidence_classes": {},
            "citations": [],
            "pending_actions": [],
            "provenance_summary": "Answer generated by Hermes synthesizer.",
            "clinical_disagreement": None,
        }
