"""
Hermes Synthesizer — merges parallel agent outputs into one answer.
Preserves evidence classes, carries citations, surfaces confirm-token actions.
"""
import json
import logging
from typing import Optional

from .planner import PlannerDecision
from services.ai_provider import model_for_agent, multilingual_suffix
from services.clinical.citation_guard import (
    validate_citations,
    build_repair_instruction,
)

logger = logging.getLogger(__name__)


SYNTHESIZER_SYSTEM = """You are Hermes, the PAL health assistant synthesizer.
Your job: merge the specialist agent outputs into ONE clear, honest answer.

Rules:
- Apply the evidence contract to every fact you surface:
  source_backed | user_canonical | inferred | statistical | unknown.
- Carry all citations from agent outputs.
- If agents disagree on something clinical, surface the disagreement honestly;
  recommend the patient speak with their clinician.
- Never diagnose, never prescribe, never interpret imaging.
- For any pending actions (booking, messaging), surface them as explicit prompts
  with confirm-token flows — never auto-send.
- Say "no good evidence found" when evidence is absent; never confabulate.
- CITATION RULE: a sentence making a clinical claim — a dose, an effect, a risk,
  a side effect, whether something works — may cite ONLY a source whose
  provenance_class is peer-reviewed-human or clinician-canonical. A pharmacy
  listing (commercial) can support a price, a pack size or a brand name and
  nothing else. This is checked after you answer.
- Never rank one medicine against another, even when asked directly. Describe
  each and send the choice to the patient's doctor.
- Language: plain, warm, non-shaming. Newsreader-quality prose.
- End with provenance summary: "Why do I think this?" answered briefly."""

SYNTHESIZER_PROMPT_TEMPLATE = """Patient query: {query}
{conversation_history_section}
Agent results:
{agent_results_json}

{record_context_section}

Synthesize one answer following the rules above. Return JSON:
{{
  "answer_text": "...",
  "evidence_classes": {{"claim": "class", ...}},
  "citations": [{{"title": "...", "source": "...", "url": "..."}}],
  "pending_actions": [{{"type": "booking|messaging", "description": "...", "confirm_token_required": true}}],
  "provenance_summary": "...",
  "clinical_disagreement": null | "description of disagreement"
}}"""


async def synthesize(
    query: str,
    agent_results: dict[str, dict],
    plan: PlannerDecision,
    ai_client,
    record_context: Optional[dict] = None,
    conversation_history: str = "",
    is_second_opinion: bool = False,
    multilingual_lang: Optional[str] = None,
) -> dict:
    record_section = ""
    if record_context:
        record_section = f"Personal record context (retrieved slice):\n{json.dumps(record_context, indent=2)}"

    history_section = ""
    if conversation_history:
        history_section = f"""**Previous conversation context:**
{conversation_history}

Use this context to maintain continuity. If the user is confirming something from a previous turn, understand what they're confirming.
"""

    prompt = SYNTHESIZER_PROMPT_TEMPLATE.format(
        query=query,
        conversation_history_section=history_section,
        agent_results_json=json.dumps(agent_results, indent=2, default=str),
        record_context_section=record_section,
    )

    system = SYNTHESIZER_SYSTEM + multilingual_suffix(multilingual_lang)
    response = await ai_client.messages.create(
        model=model_for_agent("synthesizer", is_second_opinion),
        max_tokens=2048,
        system=system,
        messages=[{"role": "user", "content": prompt}],
    )

    raw = response.content[0].text if response.content else "{}"
    try:
        # Extract JSON from the response
        start = raw.find("{")
        end = raw.rfind("}") + 1
        answer = json.loads(raw[start:end])
    except Exception:
        return {
            "answer_text": raw,
            "evidence_classes": {},
            "citations": [],
            "pending_actions": [],
            "provenance_summary": "Answer generated by Hermes synthesizer.",
            "clinical_disagreement": None,
        }

    # --- Citation guard -----------------------------------------------------
    # Runs after generation because a prompt instruction is not an enforcement
    # mechanism. One repair pass, not a loop: if the rewrite still violates,
    # ship it flagged and log it — an endless regeneration is worse for the
    # patient than an answer a reviewer can see. Both outcomes are in the logs.
    citations = answer.get("citations") or []
    guard = validate_citations(answer.get("answer_text", ""), citations)

    if not guard.ok:
        logger.warning(
            "citation guard: %d violation(s): %s",
            len(guard.violations),
            [(v.kind, v.sentence[:80]) for v in guard.violations],
        )
        try:
            repair = await ai_client.messages.create(
                model=model_for_agent("synthesizer", is_second_opinion),
                max_tokens=2048,
                system=system,
                messages=[
                    {"role": "user", "content": prompt},
                    {"role": "assistant", "content": raw},
                    {
                        "role": "user",
                        "content": (
                            build_repair_instruction(guard)
                            + "\n\nReturn the same JSON object with those problems "
                            "fixed. Keep every other field and every citation "
                            "marker exactly as it was."
                        ),
                    },
                ],
            )
            repaired_raw = repair.content[0].text if repair.content else ""
            start = repaired_raw.find("{")
            end = repaired_raw.rfind("}") + 1
            if start >= 0 and end > start:
                repaired = json.loads(repaired_raw[start:end])
                recheck = validate_citations(
                    repaired.get("answer_text", ""), repaired.get("citations") or []
                )
                answer = repaired
                if not recheck.ok:
                    logger.error(
                        "citation guard: violations survived the repair pass: %s",
                        [(v.kind, v.sentence[:80]) for v in recheck.violations],
                    )
                    answer["citation_guard_flagged"] = True
        except Exception as exc:  # noqa: BLE001 - never fail the turn on the guard
            logger.error("citation guard repair pass failed: %s", exc)
            answer["citation_guard_flagged"] = True

    return answer
