"""
Stateless HMAC confirm-token for booking / clinic messaging.

Token = HMAC-SHA256(SECRET_KEY, "{session_id}|{action_type}|{canonical_payload_json}")

The token is generated by the server when the appointment agent proposes an action,
and validated by the server when the patient clicks Confirm. No DB round-trip needed
for validation — the payload is passed back in the ConfirmActionRequest.

Write-gate: confirm-action route validates first; AppointmentRequest row is written
only after successful validation (audit + idempotency).
"""
import hashlib
import hmac
import json


def _canonical(payload: dict) -> str:
    return json.dumps(payload, sort_keys=True, separators=(',', ':'))


def generate_confirm_token(
    secret: str,
    session_id: str,
    action_type: str,
    payload: dict,
) -> str:
    msg = f"{session_id}|{action_type}|{_canonical(payload)}".encode()
    return hmac.new(secret.encode(), msg, hashlib.sha256).hexdigest()


def validate_confirm_token(
    token: str,
    secret: str,
    session_id: str,
    action_type: str,
    payload: dict,
) -> bool:
    expected = generate_confirm_token(secret, session_id, action_type, payload)
    return hmac.compare_digest(token, expected)
