"""
Universal Search router — /search
Behind feature flag UNIVERSAL_SEARCH (default off → 404).
All PHI touches go through the phi guard.
"""
import uuid
from datetime import datetime, timezone
from typing import Union, Optional

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from pydantic import BaseModel

from config import get_settings
from database import get_db
from auth import get_current_user_unified as get_current_user
from services.user_service import get_patient_by_auth_user
from models import User, ConsentBasis, Tenant, AppointmentRequest, AppointmentRequestStatus
from models.phone_user import PhoneUser
from services.hermes import HermesOrchestrator
from services.action_token import validate_confirm_token
from services.analytics.tracker import track
from dependencies.credits import require_llm_credit

router = APIRouter(prefix="/search", tags=["search"])


class SearchRequest(BaseModel):
    query: str
    tenant_id: uuid.UUID
    member_id: Optional[uuid.UUID] = None       # defaults to own record
    session_id: str
    conversation_id: Optional[uuid.UUID] = None
    on_device_classification_json: Optional[str] = None
    consent_basis: Optional[ConsentBasis] = None
    is_second_opinion: bool = False


class ConfirmActionRequest(BaseModel):
    tenant_id: uuid.UUID
    member_id: Optional[uuid.UUID] = None       # defaults to own record
    session_id: str
    action_type: str       # "booking" | "messaging"
    action_payload: dict   # same payload that was signed (must include "type" and "slots")
    confirm_token: str     # HMAC token generated by appointment agent


async def _get_tenant_or_404(tenant_id: uuid.UUID, db: AsyncSession) -> Tenant:
    result = await db.execute(select(Tenant).where(Tenant.id == tenant_id))
    tenant = result.scalar_one_or_none()
    if not tenant:
        raise HTTPException(status_code=404, detail="Tenant not found.")
    return tenant


async def _run_search(
    req: SearchRequest,
    user: User,
    db: AsyncSession,
    force_second_opinion: bool = False,
) -> dict:
    settings = get_settings()
    if not settings.universal_search:
        raise HTTPException(status_code=404, detail="Universal search is not enabled.")

    tenant = await _get_tenant_or_404(req.tenant_id, db)
    member_id = req.member_id or user.id

    orchestrator = HermesOrchestrator(
        db=db,
        tenant_id=req.tenant_id,
        member_id=member_id,
        requesting_user_id=user.id,
        session_id=req.session_id,
        privacy_mode=tenant.privacy_mode,
        conversation_id=req.conversation_id,
    )

    is_second_opinion = force_second_opinion or req.is_second_opinion
    response = await orchestrator.handle(
        query=req.query,
        on_device_classification_json=req.on_device_classification_json,
        is_second_opinion=is_second_opinion,
        consent_basis=req.consent_basis,
    )

    await track(
        db, "search_turn",
        user_id=user.id,
        source=None,
        ref_code=None,
        doctor_id=None,
        clinic_id=None,
        metadata={"tenant_id": str(req.tenant_id), "is_second_opinion": is_second_opinion},
    )

    return response


@router.post("")
async def universal_search(
    req: SearchRequest,
    current_user: Union[PhoneUser, User] = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
    _: None = Depends(require_llm_credit),
):
    return await _run_search(req, user, db)


@router.post("/second-opinion")
async def second_opinion(
    req: SearchRequest,
    current_user: Union[PhoneUser, User] = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
    _: None = Depends(require_llm_credit),
):
    """
    Same pipeline as universal_search but forces is_second_opinion=True.
    All agents escalate to Claude Sonnet; evidence agent pulls a wider PubMed set.
    Intended for patient-initiated double-check on medication or treatment advice.
    """
    return await _run_search(req, user, db, force_second_opinion=True)


@router.post("/confirm-action")
async def confirm_action(
    req: ConfirmActionRequest,
    current_user: Union[PhoneUser, User] = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """
    Executes a proposed booking or clinic message after the patient confirms.

    Token validation flow:
      1. Appointment agent generates HMAC(secret, session|action_type|canonical_payload).
      2. Frontend displays proposed action + confirm button.
      3. Patient clicks confirm → frontend sends token + original payload here.
      4. Server re-derives expected token from payload and validates with compare_digest.
      5. On success: AppointmentRequest row written; status = confirmed.
      6. Clinic dispatch (Phase 6/7) processes rows with status = confirmed.
    """
    settings = get_settings()
    if not settings.universal_search:
        raise HTTPException(status_code=404, detail="Universal search is not enabled.")

    if req.action_type not in ("booking", "messaging"):
        raise HTTPException(status_code=400, detail="action_type must be 'booking' or 'messaging'.")

    # Validate HMAC token — stateless, no DB lookup needed
    valid = validate_confirm_token(
        token=req.confirm_token,
        secret=settings.secret_key,
        session_id=req.session_id,
        action_type=req.action_type,
        payload=req.action_payload,
    )
    if not valid:
        raise HTTPException(status_code=403, detail="Invalid or expired confirm token.")

    member_id = req.member_id or user.id

    # Write audit record — dispatched by clinic connector later
    now = datetime.now(timezone.utc)
    appointment_request = AppointmentRequest(
        tenant_id=req.tenant_id,
        member_id=member_id,
        requesting_user_id=user.id,
        session_id=req.session_id,
        action_type=req.action_type,
        action_payload=req.action_payload,
        status=AppointmentRequestStatus.confirmed,
        confirmed_at=now,
    )
    db.add(appointment_request)
    await db.commit()
    await db.refresh(appointment_request)

    action_label = "appointment booking" if req.action_type == "booking" else "message to your clinic"
    return {
        "status": "confirmed",
        "request_id": str(appointment_request.id),
        "action_type": req.action_type,
        "message": (
            f"Your {action_label} has been recorded. "
            "You will receive a confirmation once the clinic processes your request."
        ),
    }
