"""
Realtime chat models — adapted from realtime-chat-kit for PAL.

ADAPTATION NOTES (vs. the kit's models.py):
  * Uses PAL's ``models.base.Base`` + ``UUIDMixin`` instead of a fresh
    DeclarativeBase. A separate Base would NOT be picked up by
    ``database.init_db()``'s ``Base.metadata.create_all`` and the tables would
    silently never be created.
  * Uses ``UUIDMixin`` only (not ``TimestampMixin``): the kit's schema has
    ``created_at`` but no ``updated_at``, and chat rows are append-only /
    soft-delete. Adding ``updated_at`` would diverge from schema.sql and from
    the alembic migration.
  * ``chat_messages.sender_id / recipient_id / room_id`` stay VARCHAR(36) with
    NO foreign keys. This is the kit's deliberate decoupling so one table can
    hold DMs, room messages and system messages. Kept as-is.
  * ``owner_org_type`` / ``owner_org_id`` on chat_rooms are used by PAL to bind
    a room to a family plan: ('family_plan', <family_plans.id>).

NO EXISTING PAL TABLE IS TOUCHED BY THIS FILE. Every table here is new.
"""
import enum
import uuid
from datetime import datetime
from typing import Optional

from sqlalchemy import (
    String, Text, Integer, Boolean, DateTime, ForeignKey, UniqueConstraint,
    Index, func, text,
)
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import Mapped, mapped_column

from .base import Base, UUIDMixin


# ── Enums (string values; stored as VARCHAR, not PG ENUM) ────────────────────
# Deliberately NOT SQLAlchemy Enum() types: creating a PG ENUM type is a
# schema-level object that complicates downgrade. Plain VARCHAR keeps the
# migration purely additive and trivially reversible.

class RoomType(str, enum.Enum):
    dm = "dm"                    # 1:1 direct message (exactly 2 members)
    group = "group"              # generic group room
    family_hub = "family_hub"    # PAL Family Care Hub (one per family plan)
    care_team = "care_team"      # patient + their clinicians


class MessageType(str, enum.Enum):
    dm = "dm"
    room = "room"
    system = "system"            # generated by PAL, no human sender


class ContentType(str, enum.Enum):
    text = "text"
    image = "image"
    file = "file"
    link = "link"
    payment_request = "payment_request"   # PAL: structured pay-link card
    care_event = "care_event"             # PAL: "appointment complete", etc.
    access_request = "access_request"     # PAL: consent handshake card


def _created_at() -> Mapped[datetime]:
    return mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )


# ── Rooms ────────────────────────────────────────────────────────────────────
class ChatRoom(Base, UUIDMixin):
    """A group channel, a Family Care Hub, or a 1:1 DM container.

    A DM is just a room with room_type='dm' and exactly two chat_room_members.
    There is no separate DM table — inbox, unread counts, history and the
    realtime path are identical for DMs and groups.
    """
    __tablename__ = "chat_rooms"

    name: Mapped[str] = mapped_column(String(300), nullable=False)
    slug: Mapped[str] = mapped_column(String(300), unique=True, index=True, nullable=False)
    room_type: Mapped[str] = mapped_column(String(50), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text)

    # NOTE: every NOT NULL column with a default carries a server_default as
    # well as a Python default. The Python default only applies to ORM inserts;
    # this module is also written to by parameterised raw SQL (the chat kit
    # style), and `database.init_db()` builds dev databases with create_all()
    # rather than alembic. Without server_default the two paths produce
    # different schemas and the raw inserts hit a NOT NULL violation.
    is_private: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True, server_default=text("true"))
    is_moderated: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True, server_default=text("true"))
    max_members: Mapped[Optional[int]] = mapped_column(Integer)
    member_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0, server_default="0")

    # Binds a room to an owning entity in PAL. For the Family Care Hub:
    #   owner_org_type = 'family_plan', owner_org_id = family_plans.id
    owner_org_type: Mapped[Optional[str]] = mapped_column(String(20), index=True)
    owner_org_id: Mapped[Optional[uuid.UUID]] = mapped_column(UUID(as_uuid=True), index=True)

    created_by: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL")
    )
    created_at: Mapped[datetime] = _created_at()

    __table_args__ = (
        Index("ix_chat_rooms_owner", "owner_org_type", "owner_org_id"),
    )

    def __repr__(self) -> str:  # pragma: no cover
        return f"<ChatRoom(id={self.id}, type={self.room_type}, slug={self.slug})>"


class ChatRoomMember(Base, UUIDMixin):
    """Who is in a group / the two people in a DM.

    This table is the ONLY authorization source for room reads and writes.
    The upstream kit shipped without a membership check; PAL enforces it in
    ``services.chat.authz`` because rooms carry PHI.
    """
    __tablename__ = "chat_room_members"

    room_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("chat_rooms.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )
    role: Mapped[str] = mapped_column(String(20), nullable=False, default="member", server_default="member")
    is_muted: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False, server_default=text("false"))
    # Set when a member is removed from a family plan; membership rows are kept
    # so historical messages still resolve a sender name.
    left_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    joined_at: Mapped[datetime] = _created_at()

    # ── read watermark ───────────────────────────────────────────────────────
    # "I have read every message in this room created at or before this time."
    #
    # Exists to make the unread badge O(unread) instead of O(history). The
    # original implementation counted unread by anti-joining every message in
    # the room against message_read_receipts: measured 27.9 ms at 15k messages
    # and 96 ms at 60k, touching 45,288 shared buffers to return the number 12,
    # and getting slower every day the family chatted. Counting forward from a
    # watermark turns the existing (room_id, created_at) index into a range
    # scan — 0.094 ms on the same data, and flat as history grows.
    #
    # NULL means "never opened this room", which correctly reads as
    # "everything is unread" via COALESCE(last_read_at, '-infinity').
    #
    # message_read_receipts is NOT removed — it still backs per-message
    # "seen by". It simply stops being the source of truth for a *count*.
    last_read_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))

    __table_args__ = (
        UniqueConstraint("room_id", "user_id", name="uq_chat_room_member"),
        # Mirrors migration 0011 so create_all() and Alembic agree.
        Index(
            "ix_chat_room_members_user_watermark",
            "user_id", "last_read_at",
            postgresql_where=text("left_at IS NULL"),
        ),
    )


# ── Messages ─────────────────────────────────────────────────────────────────
class ChatMessage(Base, UUIDMixin):
    """A DM, a room message, or a PAL system message. Soft-delete only —
    healthcare conversations are an audit record."""
    __tablename__ = "chat_messages"

    sender_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    recipient_id: Mapped[Optional[str]] = mapped_column(String(36), index=True)
    # NO standalone index here — deliberately.
    #
    # `ix_chat_messages_room_created` below is (room_id, created_at), and a
    # single-column index on room_id is a strict prefix of it: redundant for
    # lookups, but NOT harmless. With both present the planner preferred the
    # narrower room_id index for the unread-count query, then filtered
    # created_at afterwards — scanning all 15,001 messages per room to find 4.
    #
    # Measured on 60k messages, same query, only difference being this index:
    #     with    ix_chat_messages_room_id :  11.7 ms, 1,286 buffers
    #     without ix_chat_messages_room_id :   0.19 ms,    19 buffers
    #
    # Migration 0011 drops it. Adding it back re-breaks the unread badge.
    room_id: Mapped[Optional[str]] = mapped_column(String(36))

    message_type: Mapped[str] = mapped_column(String(20), nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    content_type: Mapped[str] = mapped_column(String(20), nullable=False, default="text", server_default="text")
    media_url: Mapped[Optional[str]] = mapped_column(String(500))
    reply_to_id: Mapped[Optional[str]] = mapped_column(String(36))
    msg_source: Mapped[Optional[str]] = mapped_column(String(20))

    # PAL addition: structured payload for non-text cards (payment_request,
    # access_request, care_event). Keeps `content` a human-readable fallback
    # so old clients that only render text still show something sane.
    payload: Mapped[Optional[dict]] = mapped_column(JSONB)

    # PAL addition: which family member this message is *about*, for PHI
    # filtering and audit. NULL for ordinary chatter.
    subject_member_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), index=True
    )

    is_deleted: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False, server_default=text("false"))
    deleted_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = _created_at()

    __table_args__ = (
        Index("ix_chat_messages_room_created", "room_id", "created_at"),
        Index("ix_chat_messages_dm", "sender_id", "recipient_id", "created_at"),
    )


class MessageReadReceipt(Base, UUIDMixin):
    """Unread counts and 'seen' state.

    Unread = messages from others in a room with no receipt row from me.
    """
    __tablename__ = "message_read_receipts"

    message_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("chat_messages.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )
    reader_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    read_at: Mapped[datetime] = _created_at()

    __table_args__ = (
        UniqueConstraint("message_id", "reader_id", name="uq_read_receipt"),
    )


class ChatMessageReaction(Base, UUIDMixin):
    __tablename__ = "chat_message_reactions"

    message_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    user_id: Mapped[str] = mapped_column(String(36), nullable=False)
    reaction: Mapped[str] = mapped_column(String(16), nullable=False, default="like", server_default="like")
    created_at: Mapped[datetime] = _created_at()

    __table_args__ = (
        UniqueConstraint("message_id", "user_id", "reaction", name="uq_chat_msg_reaction"),
    )


# ── Notifications ────────────────────────────────────────────────────────────
class Notification(Base, UUIDMixin):
    """In-app notification. Delivered live over the notifications WebSocket
    (or the chat socket) and persisted here for the bell / notification centre.

    NOTE: PAL had no `notifications` table before this change — verified against
    every existing __tablename__. This is a new table, not a redefinition.
    """
    __tablename__ = "notifications"

    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )
    title: Mapped[str] = mapped_column(String(300), nullable=False)
    body: Mapped[Optional[str]] = mapped_column(Text)
    notification_type: Mapped[str] = mapped_column(String(50), nullable=False)
    channel: Mapped[str] = mapped_column(String(20), nullable=False, default="in_app", server_default="in_app")
    link: Mapped[Optional[str]] = mapped_column(String(500))
    ref_id: Mapped[Optional[uuid.UUID]] = mapped_column(UUID(as_uuid=True))
    is_read: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False, server_default=text("false"))
    created_at: Mapped[datetime] = _created_at()

    __table_args__ = (
        Index("ix_notifications_user_unread", "user_id", "is_read", "created_at"),
    )
